add workflow to build apk

diff --git a/.github/workflows/build-quick-tools.yml b/.github/workflows/build-quick-tools.yml
--- a/.github/workflows/build-quick-tools.yml
+++ b/.github/workflows/build-quick-tools.yml
@@ -33,6 +33,8 @@ jobs:
         runs-on: ubuntu-latest
         permissions:
             contents: write
+        if: false
+        
         steps:
             - uses: actions/checkout@v4
 
@@ -94,3 +96,100 @@ jobs:
                   files: |
                       ${{ env.PROJECT_DIR }}/${{ env.LINUX_TARGET_DIR_TAR }}.tar.gz
                       ${{ env.PROJECT_DIR }}/${{ env.WINDOWS_FILE_NAME }}.zip
+
+    publish-android:
+        runs-on: ubuntu-latest
+
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
+
+            - name: Setup .NET
+              uses: actions/setup-dotnet@v4
+              with:
+                  dotnet-version: '8.0.x'
+
+            - name: Install MAUI Android workload
+              run: dotnet workload install maui-android
+
+            - name: Restore dependencies
+              run: dotnet restore "/QuickTools-BE/QuickTools.Mobile/QuickTools.Mobile.csproj"
+
+            - name: Decode Android keystore
+              env:
+                  ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
+              run: |
+                  echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$RUNNER_TEMP/quicktools.keystore"
+
+            - name: Build signed APK
+              env:
+                  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
+                  ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
+                  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
+              run: |
+                  cd /QuickTools-BE/QuickTools.Mobile
+
+                  dotnet publish QuickTools.Mobile.csproj \
+                    -f net8.0-android \
+                    -c Release \
+                    -p:AndroidKeyStore=true \
+                    -p:AndroidPackageFormats=apk \
+                    -p:AndroidSigningKeyStore=$RUNNER_TEMP/quicktools.keystore \
+                    -p:AndroidSigningKeyAlias="$ANDROID_KEY_ALIAS" \
+                    -p:AndroidSigningKeyPass="$ANDROID_KEY_PASSWORD" \
+                    -p:AndroidSigningStorePass="$ANDROID_KEYSTORE_PASSWORD"
+
+            - name: Verify APK
+              run: |
+                  APK=$(find bin/Release/net8.0-android/publish \
+                    -name "*-Signed.apk" \
+                    -type f | head -n 1)
+
+                  if [ -z "$APK" ]; then
+                    echo "Signed APK not found"
+                    exit 1
+                  fi
+
+                  echo "APK: $APK"
+
+            - name: Upload APK
+              uses: actions/upload-artifact@v4
+              with:
+                  name: android-release-apk
+                  path: bin/Release/net10.0-android/publish/*-Signed.apk
+
+            - name: Remove old tag if exists
+              run: |
+                  if git ls-remote --tags origin | grep -q "refs/tags/${{ env.TAG_NAME }}"; then
+                    echo "Deleting old tag..."
+                    git push origin :refs/tags/${{ env.TAG_NAME }}
+                  else
+                    echo "No old tag found."
+                  fi
+
+            - name: Delete existing release
+              run: |
+                  gh release delete ${{ env.TAG_NAME }} --yes || echo "No release to delete"
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+            - name: Create Tag
+              run: |
+                  git config user.name "github-actions"
+                  git config user.email "github-actions@github.com"
+                  git tag ${{ env.TAG_NAME }}
+                  git push origin ${{ env.TAG_NAME }}
+
+            - name: Create Release
+              uses: softprops/action-gh-release@v1
+              with:
+                  draft: false
+                  name: ${{ env.RELEASE_NAME }}
+                  tag_name: ${{ env.TAG_NAME }}
+                  generate_release_notes: true
+                  files: |
+                      ${{ env.PROJECT_DIR }}/${{ env.LINUX_TARGET_DIR_TAR }}.tar.gz
+                      ${{ env.PROJECT_DIR }}/${{ env.WINDOWS_FILE_NAME }}.zip
+                      ${{ env.PROJECT_DIR }}/QuickTools-BE/QuickTools.Mobile/bin/Release/net8.0-android/publish/com.newtun.quicktools-Signed.apk
+
+
